### ISSUE TITLE
I want to go NEO DevCon! My email: thecoinjunkie@gmail.com

### ISSUE THREAD

**Issue by ghost** [neo-project/neo.org#55]
I am not a developer but would like to cover the event from a press point of view. Would love to conduct some interviews and discuss further development of the neo platform. I have a growing number of followers on social media as well as youtube.

**Comment by chenzhitong** [comment]
Sorry, the free tickets are only for developers who have contributed to the GitHub. @TheCoinJunkie

**Comment by TheCoinJunkie** [comment]
And if 100 devs don't reply or accept your offer ?

**Comment by TheCoinJunkie** [comment]
Have just went through and notated all of the non-developers that have received free tickets.

**Comment by TheCoinJunkie** [comment]
You should either follow your own rules or get someone who can

**Comment by 4math2379** [comment]
Ok now I understand why you come « discuss » on my issue. At your place I will be disappointed too. But as I said in my demand. 
- i’am not for the moment a Neo Dev. 
- I am a smart contract developer with the ETH Neto work ( I can send you a key of a crypto I can made espcialy for you ) 
- I am a strong backend developer : nodejs , JavaScript and python. 
- my repo are not only on GitHub, got some on bitBucket and Beanstalk. 
So please you should stop be aggressive and said I am not what I said. 

Neo is a community.  You should respect that. 

And I wanna know « people you know » who receive a negative réponse because they are not developer. 
You ask it was because of that you ask the question in my issue. 

Regards 
4math

**Comment by 4math2379** [comment]
I mean ETH NETWORK * ( auto correction sorry )

**Comment by TheCoinJunkie** [comment]
It wasn't just your just you there are numerous others. Go look for yourself and give me your honest feedback as to if you think they aren't being fair not only myself but many others. And you will see my same comment on all the others as well.

**Comment by TheCoinJunkie** [comment]
Look through them all and tell me you don't see something strange going on
