### ISSUE TITLE
I want to go to NEO DevCon! My email: msiedlecki@gmail.com

### ISSUE THREAD

**Issue by msied** [neo-project/neo.org#73]
I'm a full-stack JavaScript developer who has worked at several seed stage YC startups in Silicon Valley. I built and run a mobile app that services rideshare drivers, and I lead product at a voice analytics startup. I'm interested in applying my skills in the blockchain space.

**Comment by chenzhitong** [comment]
The Promotional Code has been sent to your mailbox, please check your mailbox. @msied

**Comment by TheCoinJunkie** [comment]
How is this person a developer who has contributed to the github ?

**Comment by msied** [comment]
@TheCoinJunkie Might be misworded. I think they meant you need to have a history of using github via contributing to projects, showing code / proof of development. Not necessarily the neo repos.

**Comment by TheCoinJunkie** [comment]
Not at all. I found many people who were awarded who had absolutely no history of github repository, literally very first commit was asking for a ticket and they were awarded

**Comment by chenzhitong** [comment]
As long as he's a developer, he doesn't have to be a neo developer. I will look at the GitHub of each submitter, and if there is no contribution, I cannot send him tickets. Others have Repositories, Stars and Followers in his GitHub. But you don't have any Repositories in GitHub. You should reflect on yourself instead of questioning others.
@TheCoinJunkie
